[build]
  command = "npm run build"
  publish = "_site"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/work/*"

  [headers.values]
    # stop Google indexing work pages so they stay semi-private
    X-Robots-Tag = "noindex"